/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "AudioTool.h"

#ifndef _Included_lib_zxtcode_com_mylib_AudioTool
#define _Included_lib_zxtcode_com_mylib_AudioTool
#ifdef __cplusplus
extern "C" {
#endif
#undef lib_zxtcode_com_mylib_AudioTool_INIT_TYPE
#define lib_zxtcode_com_mylib_AudioTool_INIT_TYPE -1L
#undef lib_zxtcode_com_mylib_AudioTool_AMR_NB_TYPE
#define lib_zxtcode_com_mylib_AudioTool_AMR_NB_TYPE 1L
#undef lib_zxtcode_com_mylib_AudioTool_AMR_WB_TYPE
#define lib_zxtcode_com_mylib_AudioTool_AMR_WB_TYPE 2L

JNIEXPORT void JNICALL Java_lib_zxtcode_com_mylib_AudioTool_joinAMRFiles
        (JNIEnv *, jclass, jobjectArray, jstring);

JNIEXPORT void JNICALL Java_lib_zxtcode_com_mylib_AudioTool_splitAMRFiles
        (JNIEnv *, jclass, jobjectArray, jstring);

JNIEXPORT int JNICALL Java_lib_zxtcode_com_mylib_AudioTool_isAMRFile
        (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
